<?php

function housing_schemes_services_services_resources() {
  $resources = array();

  //Include the necessary inc files.
  module_load_include('inc', 'housing_schemes_services', 'housing_schemes.services');

  //Service Apis for contents.
  $resources += housing_schemes_services_resource();

  return $resources;
}

function housing_schemes_services_resource_retrieve($nid) {
  $node = node_load($nid);
  //Check if the node type is housing schemes.
  if ($node->type == 'housing_scheme') {
    //Get PROPERTY DESCRIPTION data from field collection.
    $property_description = $node->body[LANGUAGE_NONE][0]['value'];
    // here we are loading field collection
    $pd_item = field_collection_item_load($property_description);

     $return_obj = array(
      'scheme_name' => $node->title,
      'scheme_id' => $node->nid,
      'created_date' => $node->created,
      'about_scheme'=>$node->body[LANGUAGE_NONE][0]['value'],
      'distance_from_the_city'=>$node->field_distance_from_the_city[LANGUAGE_NONE][0]['value'],
      'nearest_major_city' => $node->field_nearest_major_city[LANGUAGE_NONE][0]['value'],
      'distance_from_the_city' => $node->field_distance_from_the_city[LANGUAGE_NONE][0]['value'],
      'locality_review' =>$node->field_locality_review[LANGUAGE_NONE][0]['value'],  
      //'property_description' => $pd_item_values,
    );
  }
  return $return_obj;
}